---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snipeit-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: snipeit
  replicas: 1
  template:
    metadata:
      labels:
        app: snipeit
    spec:
      containers:
      - name: snipeit
        image: lscr.io/linuxserver/snipe-it:latest
        imagePullPolicy: Always
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: "America/Denver"
        - name: APP_URL
          value: https://inventory.sancaktar.net
        - name: APP_TRUSTED_PROXIES
          value: 10.10.8.0/23
        - name: APP_ALLOW_INSECURE_HOSTS
          value: "true"
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: "mysql-service"
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: snipeit
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: snipeit
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: snipeit
              key: password
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /data
          name: snipeit-data
      volumes:
      - name: snipeit-data
        nfs:
          server: 10.10.9.14
          path: "/mnt/Storage/apps/snipeit"