---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzb-config-claim
  namespace: mediastack
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: mayastor
