---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli-deployment
  namespace: mediastack
spec:
  selector:
    matchLabels:
      app: tautulli
  replicas: 1
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      containers:
      - name: tautulli
        image: lscr.io/linuxserver/tautulli:latest
        env:
        - name: PUID
          value: "1000"
        - name: GUID
          value: "1000"
        - name: TZ
          value: "America/Denver"
        ports:
        - containerPort: 8181
        volumeMounts:
        - mountPath: /config
          name: tautulli-config
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      volumes:
      - name: tautulli-config
        persistentVolumeClaim:
          claimName: tautulli-config-pvc