---
apiVersion: v1
kind: Service
metadata:
  name: overseerr-service
  namespace: mediastack
spec:
  selector:
    app: overseerr
  ports:
    - name: overseerr-web
      port: 80
      targetPort: 5055
      protocol: TCP
