---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-config-pvc
  namespace: mediastack
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: "mayastor"
