---
  apiVersion: v1
  kind: Service
  metadata:
    name: nextcloud
    namespace: nextcloud
  spec:
    ports:
    - port: 80
      targetPort: 4043
      name: nc-web
      protocol: TCP
    - port: 5433
      targetPort: 5432
      name: nc-db
    - port: 80
      targetPort: 9980
      name: nc-oo
    selector:
      app: nextcloud
    type: LoadBalancer
    loadBalancerIP: 10.10.9.180
