---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: default
spec:
  selector:
    matchLabels:
      app: paperless
  replicas: 1
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
      - name: paperless
        image: lscr.io/linuxserver/paperless-ngx:latest
        imagePullPolicy: Always
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: PAPERLESS_TIME_ZONE
          value: "America/Denver"
        - name: PAPERLESS_URL
          value: https://docs.sancaktar.net
        - name: PAPERLESS_OCR_LANGUAGE
          value: eng
        - name: USERMAP_UID
          value: "1000"
        - name: USERMAP_GID
          value: "1000"
        - name: PAPERLESS_PORT
          value: "8000"
        - name: PAPERLESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: paperless-key
              name: paperless-secret
        # - name: PAPERLESS_DBNAME
        #   valueFrom:
        #     secretKeyRef:
        #       key: dbname
        #       name: paperless-secret
        # - name: PAPERLESS_DBUSER
        #   valueFrom:
        #     secretKeyRef:
        #       key: dbuser
        #       name: paperless-secret
        # - name: PAPERLESS_DBPASS
        #   valueFrom:
        #     secretKeyRef:
        #       key: dbpass
        #       name: paperless-secret
        # - name: PAPERLESS_DBHOST
        #   valueFrom:
        #     secretKeyRef:
        #       key: dbhost
        #       name: paperless-secret
        

        ports:
        - name: paperless-port
          containerPort: 8000
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/consume
          name: paperless-incoming
        - mountPath: /data/export
          name: paperless-media
        - mountPath: /data/media
          name: paperless-export
        - mountPath: /config
          name: paperless-config
        resources:
          limits:
            cpu: "2000m"
            memory: "512Mi"
          requests:
            cpu: "50m"
            memory: "256Mi"
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "curl -f http://localhost:8000"
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5

      volumes:
      - name: paperless-incoming
        nfs:
          server: 10.10.9.14
          path: /mnt/Storage/apps/paperless/incoming
      - name: paperless-media
        nfs:
          server: 10.10.9.14
          path: /mnt/Storage/apps/paperless/media
      - name: paperless-export
        nfs:
          server: 10.10.9.14
          path: /mnt/Storage/apps/paperless/export
      - name: paperless-config
        persistentVolumeClaim:
          claimName: paperless-config-pvc
      restartPolicy: Always