---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paperless-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: "mayastor"