---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-udp
  namespace: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-10.10.9.182"
spec:
  selector:
    app: unifi
  ports:
    - name: stun
      port: 3478
      protocol: UDP
    - name: unifi-disc
      port: 10001
      protocol: UDP
    - name: unifi-disc-l2
      port: 1900
      protocol: UDP
  type: LoadBalancer
  loadBalancerIP: 10.10.9.182
