apiVersion: batch/v1
kind: CronJob
metadata:
  name: plex-media-manager
  namespace: mediastack
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          # securityContext:
          #   runAsUser: 911
          #   runAsGroup: 1001
          containers:
            - name: plex-media-manager
              image: linuxserver/plex-meta-manager
              imagePullPolicy: IfNotPresent
              args: [ "--run", "--read-only-config" ]
              resources:
                limits:
                  cpu: 100m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 125Mi
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: pmm-config
                  mountPath: /config/config.yml
                  subPath: config.yml
                - name: movie-config
                  mountPath: /config/movies.yaml
                  subPath: movies.yaml
                - name: tv-config
                  mountPath: /config/tv.yaml
                  subPath: tv.yaml
          dnsConfig:
            options:
            - name: ndots
              value: "2"

          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: plex-media-manager
            - configMap:
                name: pmm-config
              name: pmm-config
            - configMap:
                name: movie-config
              name: movie-config
            - configMap:
                name: tv-config
              name: tv-config
          restartPolicy: OnFailure