apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-manager
  namespace: mediastack
  labels:
    app: plex-media-manager
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: mayastor