---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome-deployment
spec:
  selector:
    matchLabels:
      app: esphome
  replicas: 1
  template:
    metadata:
      labels:
        app: esphome
    spec:
      containers:
      - name: esphome
        image: esphome/esphome
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "99"
        - name: PGID
          value: "100"
        - name: ESPHOME_DASHBOARD_USE_PING
          value: "true"
        ports:
        - containerPort: 6052
        volumeMounts:
        - mountPath: /old
          name: esphome-volume
        - mountPath: /config
          name: esphome-data
      volumes:
      - name: esphome-volume
        persistentVolumeClaim:
          claimName: esphome-config-pvc
      - name: esphome-data
        nfs:
          server: 10.10.9.14
          path: /mnt/Storage/apps/espHome/data
      dnsConfig:
        options:
        - name: ndots
          value: "2"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
