---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: esphome-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: "mayastor"